# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b9e0bc8401e3f1cdd9dc66c430e6cebc0cb0fbbeebdaf76dff0f9bdfe51b070589709734ed50854b19ccfa92f9fd3481b8ef9231df366fb495e10eaa6c3ac0f

test:
  secret_key_base: b98837987d46fc805ea4f993d5b4edc109f8b2ef85ad500a0e0bbe93faedcaab5c92e4dfc94b51e7ba84b25fa88b406d776d6061a66d11dc35bbc297d94f421c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
